# Introducción {#intro}

En este libro-tutorial realizaremos simulaciones de datos para modelos de ocupación, bajo el modelo estático de una sola estación, desarrollado originalmente por Daryl MacKenzie [@MacKenzie2002]. El modelo básico de ocupación, es la piedra angular del muestreo y monitoreo biológico moderno!.

El objetivo de este documento es entender la versatilidad y el poder de las simulaciones con R en el capítulo \@ref(why). Aprenderemos el principio biologico y el mecanismo bajo el cual funciona el modelo básico de ocupación en el capítulo \@ref(occu). Realizaremos un ejemplo sencillo en el capítulo \@ref(example) para un venado del Parque Nacional Machalilla. Posteriormente empacaremos el código que genera los datos de ocupación, en una sola función en el Capítulo \@ref(function1). Esta función nos permitirá simular datos bajo diferentes escenarios, los cuales analizaremos con los estimadores de máxima verosimilitud de la función occu del paquete unmarked en el Capítulo \@ref(unmarked). Posteriormente analizaremos los mismos datos bajo estimadores bayesianos en el Capítulo \@ref(bayesian), para al final comparar la precisión de ambas aproximaciones, máxima verosimilitud y bayesiana.


#### Créditos

Gran parte del concepto de este documento, el código y el texto han sido adaptados de los libros de [Marc Kery](http://store.elsevier.com/Marc-Kery/ELS_1059944/) [@Kery2012; @Kery2010; @kery2015applied].


